"""Tome-centered public contract surface."""

from radjax_contract.tome.compression import (
    TomeCompression,
    TomeCompressionFamily,
    valid_compression_for_payload,
)
from radjax_contract.tome.contract_publication import (
    TOME_CONTRACT_ID,
    TOME_CONTRACT_PUBLICATION_VERSION,
    TOME_STREAMING_CONTRACT_PUBLICATION_VERSION,
    TOME_STUDENT_CONSUMPTION_CONTRACT_ID,
    TOME_STUDENT_CONSUMPTION_CONTRACT_PUBLICATION_VERSION,
    TOME_STUDENT_CONSUMPTION_V2_CONTRACT_PUBLICATION_VERSION,
    tome_contract_asset_path,
    tome_contract_root,
    tome_streaming_contract_asset_path,
    tome_streaming_contract_root,
    tome_student_consumption_contract_asset_path,
    tome_student_consumption_contract_root,
    tome_student_consumption_v2_contract_asset_path,
    tome_student_consumption_v2_contract_root,
)
from radjax_contract.tome.cover_page import (
    TomeBehavioralSummary,
    TomeContentsSummary,
    TomeCorpusSource,
    TomeCorpusSummary,
    TomeCoverPage,
    TomeCoverPageLoadResult,
    TomeExemplarSummary,
    TomeSplitSummary,
    TomeStudentConsumptionSummary,
    TomeTeacherSummary,
    load_tome_cover_page,
)
from radjax_contract.tome.inspection import (
    TomeConsumptionPlan,
    inspect_tome_for_consumption,
)
from radjax_contract.tome.manifest import TomeManifest, TomeRole
from radjax_contract.tome.payloads import TomePayloadFormat
from radjax_contract.tome.production import (
    ArtifactLocalFingerprintId,
    ArtifactLocalModeId,
    ProductionTomeArtifact,
    ProductionTomeInspection,
    ProductionTomeValidationResult,
    inspect_production_tome,
    load_production_tome,
    validate_production_tome,
)
from radjax_contract.tome.records import (
    TomeRecord,
    TomeRecordLoadResult,
    load_tome_records,
)
from radjax_contract.tome.shards import TomeShard
from radjax_contract.tome.streaming_validation import (
    Result as StreamingTomeValidationResult,
)
from radjax_contract.tome.streaming_validation import (
    StreamingTomeDescriptor,
    StreamingTomeReader,
    open_streaming_tome,
    read_extracted_payload_record,
    validate_streaming_tome,
)
from radjax_contract.tome.student_consumption import (
    ResolvedStudentResource,
    StudentConsumptionDescriptor,
    StudentConsumptionIssue,
    StudentConsumptionValidationResult,
    open_verified_student_resource,
    validate_and_resolve_student_consumption,
)
from radjax_contract.tome.student_consumption_v2 import (
    ResolvedStudentConsumptionV2Resource,
    StudentConsumptionV2Descriptor,
    StudentConsumptionV2ValidationResult,
    open_verified_student_resource_v2,
    validate_and_resolve_student_consumption_v2,
)
from radjax_contract.tome.validation import (
    TomeValidationResult,
    validate_tome,
    validate_tome_split_disjointness,
)

__all__ = [
    "ArtifactLocalFingerprintId",
    "ArtifactLocalModeId",
    "TOME_CONTRACT_ID",
    "TOME_CONTRACT_PUBLICATION_VERSION",
    "TOME_STREAMING_CONTRACT_PUBLICATION_VERSION",
    "TOME_STUDENT_CONSUMPTION_CONTRACT_ID",
    "TOME_STUDENT_CONSUMPTION_CONTRACT_PUBLICATION_VERSION",
    "TOME_STUDENT_CONSUMPTION_V2_CONTRACT_PUBLICATION_VERSION",
    "ProductionTomeArtifact",
    "ProductionTomeInspection",
    "ProductionTomeValidationResult",
    "ResolvedStudentResource",
    "StudentConsumptionDescriptor",
    "StudentConsumptionIssue",
    "StudentConsumptionValidationResult",
    "ResolvedStudentConsumptionV2Resource",
    "StudentConsumptionV2Descriptor",
    "StudentConsumptionV2ValidationResult",
    "open_verified_student_resource",
    "open_verified_student_resource_v2",
    "TomeBehavioralSummary",
    "TomeCompression",
    "TomeCompressionFamily",
    "TomeConsumptionPlan",
    "TomeContentsSummary",
    "TomeCorpusSource",
    "TomeCorpusSummary",
    "TomeCoverPage",
    "TomeCoverPageLoadResult",
    "TomeExemplarSummary",
    "TomeManifest",
    "TomePayloadFormat",
    "TomeRecord",
    "TomeRecordLoadResult",
    "TomeRole",
    "TomeShard",
    "TomeSplitSummary",
    "TomeStudentConsumptionSummary",
    "TomeTeacherSummary",
    "TomeValidationResult",
    "StreamingTomeValidationResult",
    "StreamingTomeDescriptor",
    "StreamingTomeReader",
    "inspect_tome_for_consumption",
    "inspect_production_tome",
    "load_tome_cover_page",
    "load_tome_records",
    "open_streaming_tome",
    "read_extracted_payload_record",
    "tome_contract_asset_path",
    "tome_contract_root",
    "tome_streaming_contract_asset_path",
    "tome_streaming_contract_root",
    "tome_student_consumption_contract_asset_path",
    "tome_student_consumption_contract_root",
    "tome_student_consumption_v2_contract_asset_path",
    "tome_student_consumption_v2_contract_root",
    "load_production_tome",
    "valid_compression_for_payload",
    "validate_tome",
    "validate_streaming_tome",
    "validate_tome_split_disjointness",
    "validate_production_tome",
    "validate_and_resolve_student_consumption",
    "validate_and_resolve_student_consumption_v2",
]
